Repository Deltares/Wflow.jl, pull requests merged in 2024-04, with the labels that each got.

#384 Improve spelling and grammar in the modeling documentation
  docs/src/model_docs/model_configurations.md
  docs/src/model_docs/shared_concepts.md
  docs/src/model_docs/vertical/sbm.md
  docs/src/model_docs/vertical/sediment.md
Labels: documentation, v1.0

#388 Replace non-ASCII characters by ASCII characters in the names of variables, structs, functions and macros
  docs/src/changelog.md
  docs/src/index.md
  docs/src/model_docs/lateral/kinwave.md
  docs/src/model_docs/lateral/sediment_flux.md
  docs/src/model_docs/params_lateral.md
  docs/src/model_docs/params_vertical.md
  docs/src/model_docs/shared_concepts.md
  docs/src/model_docs/structures.md
  docs/src/model_docs/vertical/flextopo.md
  docs/src/model_docs/vertical/sbm.md
  docs/src/model_docs/vertical/sediment.md
  docs/src/user_guide/model-setup.md
  docs/src/user_guide/step2_settings_file.md
  docs/src/user_guide/step4_running.md
  server/test/client.jl
  src/Wflow.jl
  src/bmi.jl
  src/flextopo.jl
  src/flextopo_model.jl
  src/flow.jl
  src/groundwater/aquifer.jl
  src/groundwater/boundary_conditions.jl
  src/groundwater/connectivity.jl
  src/hbv.jl
  src/hbv_model.jl
  src/horizontal_process.jl
  src/io.jl
  src/reservoir_lake.jl
  src/sbm.jl
  src/sbm_gwf_model.jl
  src/sbm_model.jl
  src/sediment.jl
  src/sediment_model.jl
  src/utils.jl
  src/vertical_process.jl
  test/bmi.jl
  test/groundwater.jl
  test/horizontal_process.jl
  test/io.jl
  test/reservoir_lake.jl
  test/run_sbm.jl
  test/run_sbm_gwf.jl
  test/testing_utils.jl
Labels: v1.0

#397 Fix broken doc links
  docs/src/changelog.md
  docs/src/model_docs/lateral/local-inertial.md
  docs/src/model_docs/model_configurations.md
  docs/src/user_guide/additional_options.md
  docs/src/user_guide/model-setup.md
Labels: bug, documentation
